frontend/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='index'),
    path('create/', views.CreateProjectView.as_view(), name='create_project'),
    path('<slug:slug>/', views.ProjectDetailView.as_view(), name='project_detail'),
]

mcmods/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('', include('frontend.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

frontend/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.shortcuts import reverse

import enum


class GameVersion(models.Model):
    name = models.CharField(max_length=16)
    release_date = models.DateTimeField()


class ProjectMembershipTypes(enum.IntEnum):
    OWNER = enum.auto()
    MEMBER = enum.auto()


class ReleaseChannels:
    ALPHA = 1
    BETA = 2
    RELEASE = 3


RELEASE_CHANNEL_NAMES = (
    (ReleaseChannels.ALPHA, "Alpha"),
    (ReleaseChannels.BETA, "Beta"),
    (ReleaseChannels.RELEASE, "Release"),
)


class ProjectMembership(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey("Project", on_delete=models.CASCADE)
    type = models.IntegerField()


class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    logo = models.ImageField()
    last_updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField()

    members = models.ManyToManyField(User, through=ProjectMembership)

    def __str__(self):
        return f"<Project: {self.name}>"

    def get_absolute_url(self):
        return reverse("project_detail", kwargs={"slug": self.slug})


class Release(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    game_version = models.ForeignKey(GameVersion, on_delete=models.PROTECT)
    name = models.CharField(max_length=255)
    channel = models.SmallIntegerField(choices=RELEASE_CHANNEL_NAMES)
    release_date = models.DateTimeField(default=now)


class Download(models.Model):
    release = models.ForeignKey(Release, on_delete=models.CASCADE)
    human_name = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    downloads = models.BigIntegerField()
    file = models.FileField()

frontend/forms.py
from django import forms

from .models import Project


class CreateProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name"]

frontend/views.py
import functools

from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView

from .forms import CreateProjectForm
from .models import Project, GameVersion


def index(request):
    projects = Project.objects.all()
    return render(request, "frontend/index.html", {"projects": projects})


class ProjectListView(ListView):
    queryset = Project.objects.order_by("-last_updated")
    paginate_by = 10
    template_name = "frontend/index.html"
    context_object_name = "projects"


class ProjectDetailView(DetailView):
    queryset = Project.objects.all()
    context_object_name = "project"
    template_name = "frontend/project.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["game_versions"] = list(map(functools.partial(ProjectDetailView.annotate_project_releases, context["project"]),
                                            GameVersion.objects.filter(release__in=context[
                                                "project"].release_set.all()).distinct()))  # without distinct(), the QuerySet lists each GameVersion as often as releases reference it
        return context

    @staticmethod
    def annotate_project_releases(project: Project, game_version: GameVersion):
        releases = game_version.release_set.filter(project=project).order_by("-release_date")
        result_releases = []
        for channel in range(1, 4):
            result_releases.extend(releases.filter(channel=channel)[:1])
        game_version.project_releases = result_releases
        return game_version

class CreateProjectView(CreateView):
    form_class = CreateProjectForm

frontend/templates/frontend/index.html
{% for project in projects %}
    <a href="{% url 'project_detail' project.slug %}">
        <table>
            <tbody>
                <tr>
                    <td rowspan="2">
                        <img src="{{ project.logo.url }}" />
                    </td>
                    <td>
                        {{ project.name }}
                    </td>
                </tr>
                <tr>
                    <td>
                        {{ project.description }}
                    </td>
                </tr>
            </tbody>
        </table>
    </a>
{% endfor %}
{% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endif %}

frontend/templates/frontend/project.html
<body>
<img src="{{ project.logo.url }}"/><br/>
<span>{{ project.name }}</span>
<div>
    {{ project.description }}
</div>

{% for game_version in game_versions %}
    <div>
        <br/>
        <span style="font-size: 1.3em">{{ game_version.name }}</span><br/><br/>
        {% for release in game_version.project_releases %}
            {% if release.channel == 0 %}
            {% endif %}
            <a href="{{ release.download_set.all.0.file.url }}">
                <div>
                    {{ release.get_channel_display }} {{ release.name }}
                </div>
            </a>
        {% endfor %}
    </div>
{% endfor %}
</body>